import type { Blog, Property } from "./types"

export const mockBlogs: Blog[] = [
  {
    id: 1,
    title: "Welcome to Sadef Real-Estate Blog",
    excerpt: "Latest insights about the Saudi property market and investment opportunities.",
    content:
      "<p>This is a demo blog post served from local mock data. Stay tuned for more updates about the real estate market in Saudi Arabia.</p><p>Sadef Real Estate Development continues to lead the market with innovative residential projects that offer excellent investment returns.</p>",
    imageUrl: "/images/SAFA 052.jpg",
    publishedDate: new Date().toISOString(),
    author: "Sadef Team",
    tags: ["News", "Market", "Investment"],
  },
  {
    id: 2,
    title: "Real Estate Investment Trends in Jeddah",
    excerpt: "Exploring the latest trends and opportunities in Jeddah's real estate market.",
    content:
      "<p>Jeddah's real estate market continues to show strong growth potential with new developments and infrastructure projects.</p><p>Key factors driving the market include Vision 2030 initiatives and increased foreign investment.</p>",
    imageUrl: "/images/SAFA 01.jpg",
    publishedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    author: "Market Analyst",
    tags: ["Jeddah", "Investment", "Trends"],
  },
  {
    id: 3,
    title: "Sustainable Development in Modern Real Estate",
    excerpt: "How Sadef is incorporating sustainable practices in residential developments.",
    content:
      "<p>Sustainability is at the core of modern real estate development. Our projects incorporate green building practices and energy-efficient designs.</p>",
    imageUrl: "/images/SAFA 03.jpg",
    publishedDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    author: "Development Team",
    tags: ["Sustainability", "Development", "Green Building"],
  },
]

export const mockProperties: Property[] = [
  {
    id: 1,
    name: "Al-Rawda Residence",
    description:
      "Premium apartments in the heart of Jeddah with modern amenities and excellent connectivity to major business districts.",
    location: "Jeddah",
    propertyType: "Apartment",
    bedrooms: 3,
    bathrooms: 2,
    area: "175 m²",
    startingPrice: "SAR 850,000",
    rentalYield: "8%",
    resaleValue: "SAR 1,050,000",
    annualReturn: "12%",
    imageUrl: "/images/SAFA 01.jpg",
    images: ["/images/SAFA 01.jpg", "/images/SAFA 02.jpg", "/images/SAFA 03.jpg"],
    status: "Available",
    completionDate: "Q4 2025",
    features: ["Swimming Pool", "Fitness Center", "Covered Parking", "24/7 Security", "Children's Play Area"],
    badge: "Featured",
  },
  {
    id: 2,
    name: "Corniche Tower",
    description: "Luxury high-rise apartments with stunning sea views and premium finishes.",
    location: "Jeddah Corniche",
    propertyType: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: "145 m²",
    startingPrice: "SAR 720,000",
    rentalYield: "9%",
    resaleValue: "SAR 890,000",
    annualReturn: "11%",
    imageUrl: "/images/SAFA 085.jpg",
    images: ["/images/SAFA 085.jpg", "/images/SAFA 101.jpg"],
    status: "Available",
    completionDate: "Q2 2026",
    features: ["Sea View", "Balcony", "Central AC", "Parking", "Concierge Service"],
    badge: "New",
  },
  {
    id: 3,
    name: "Garden Villas",
    description: "Spacious family villas with private gardens in a gated community.",
    location: "North Jeddah",
    propertyType: "Villa",
    bedrooms: 4,
    bathrooms: 3,
    area: "320 m²",
    startingPrice: "SAR 1,450,000",
    rentalYield: "7%",
    resaleValue: "SAR 1,750,000",
    annualReturn: "10%",
    imageUrl: "/images/SAFA 052.jpg",
    images: ["/images/SAFA 052.jpg"],
    status: "Coming Soon",
    completionDate: "Q1 2027",
    features: ["Private Garden", "Garage", "Maid's Room", "Gated Community", "Playground"],
    badge: "Premium",
  },
]
